// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnjttgmjjikmdrypvknp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuanR0Z21qamlrbWRyeXB2a25wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5ODcxOTUsImV4cCI6MjA2MzU2MzE5NX0.hG86IdZ0MCtOCkIJyTcleB4iL4KuDurK53IUKNebm5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);