// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nencukkywgbjgrlqmilf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lbmN1a2t5d2diamdybHFtaWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODA3MDAsImV4cCI6MjA2Mzg1NjcwMH0.-L9OFQdirquPkQnpx0UOwayh-l42_rurSRLQG_OyMKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);